defaults:
  - _self_
  - model: motion_lm
  - env: merge
  - data: highway
  - trainer: default

max_agents: 20

seed: 42
num_episodes: 5
render: true
viz_dir: visualizations
trainer:
  max_steps: 5000
  accelerator: auto
  devices: 1
  precision: 32-true
  log_every_n_steps: 10
