import torch
import numpy as np
import matplotlib.pyplot as plt
import os
from tqdm import tqdm
from src.utils.tokenizer import MotionTokenizer
from src.data.dataset import TrajectoryDataset

def test_raw_dataset(data_dir, num_samples=100):
    tokenizer = MotionTokenizer()
    dataset = TrajectoryDataset(
        data_dir=data_dir,
        max_agents_per_scene=20,
        sample_ratio=1.0,
        use_cache=False # Force regeneration of samples with new logic
    )
    
    os.makedirs("images/test_raw", exist_ok=True)
    
    total_error = 0
    total_points = 0
    high_error_count = 0
    
    print(f"Testing raw TrajectoryDataset on {num_samples} samples...")
    
    for i in tqdm(range(min(num_samples, len(dataset)))):
        sample = dataset[i]
        
        # sample['tokens'] are freshly generated by TrajectoryDataset.__getitem__
        # with our new initial_delta logic.
        tokens_stored = sample['tokens'].numpy()
        gt_futures = sample['gt_future'].numpy()
        masks = sample['m_mask'].numpy()
        init_deltas = sample['initial_deltas'].numpy()
        
        N_max, T_total, _ = gt_futures.shape
        T_pred = T_total - 1
        
        for n in range(N_max):
            if masks[n].sum() < 2:
                continue
                
            agent_tokens = [tokens_stored[t * N_max + n] for t in range(T_pred)]
            valid_tokens = [t for t in agent_tokens if t < 169] # 169 is INVALID_TOKEN
            
            start_pos = gt_futures[n][0]
            idelta = init_deltas[n]
            
            traj_recon = tokenizer.reconstruct_trajectory(start_pos, valid_tokens, initial_delta=idelta)
            traj_gt = gt_futures[n][masks[n] > 0]
            
            L = min(len(traj_gt), len(traj_recon))
            diff = traj_gt[:L] - traj_recon[:L]
            rmse = np.sqrt(np.mean(np.sum(diff**2, axis=1)))
            max_err = np.max(np.sqrt(np.sum(diff**2, axis=1)))
            
            total_error += np.sum(np.sqrt(np.sum(diff**2, axis=1)))
            total_points += L
            
            if max_err > 0.5:
                high_error_count += 1
                plt.figure(figsize=(10, 6))
                plt.plot(traj_gt[:, 0], traj_gt[:, 1], 'g-', label='Ground Truth', alpha=0.3)
                plt.plot(traj_recon[:, 0], traj_recon[:, 1], 'r--', label='Reconstructed', alpha=0.8)
                plt.title(f"Sample {i} Agent {n} | RMSE: {rmse:.4f} | Max Err: {max_err:.4f}")
                plt.legend()
                plt.axis("equal")
                plt.savefig(f"images/test_raw/error_s{i}_a{n}.png")
                plt.close()

    print(f"\nRaw Dataset Test Finished.")
    print(f"Total points: {total_points}")
    print(f"Average Error: {total_error / total_points:.6f}m")
    print(f"High error count: {high_error_count}")

if __name__ == "__main__":
    DATA_DIR = 'data/trajectories/hdv_1000_ep_abs_coords'
    test_raw_dataset(DATA_DIR, num_samples=100)
